apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    volume: db-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  capacity:
    storage: 1Gi
  nfs:
    server: 161.35.181.17
    path: /share

